### PR TITLE
Toolbar implementation

### PR DESCRIPTION
**Pull request by MCGallaspy**
A WIP. Getting my feet wet with this module/the win32 API/ctypes. I've been (slowly) trying to get toga-demo working.

### CODE REVIEW

**Comment by MCGallaspy** [comment]
So I opened this PR to get a preliminary look, since I'm not so familiar with ctypes & win32. On the right track?

**Comment by freakboy3742** [comment]
This is fantastic - I haven't had a chance to fire this up on a Win32 box, but by inspection it definitely looks like you're on the right track!

The only cautionary note that I'll flag is that I'm in the process of changing the Cassowary-based layout to using a CSS-based scheme. This won't change the bulk of the widgets - a button is still going to be a button, and so on - but the mechanism for determining the size and position of that button will be changing a bit.

This shouldn't affect you in the short term; once I've got a better handle on the CSS stuff I should be able to assist on any migration that is required.

**Comment by MCGallaspy** [comment]
Groovy, FYI I'm still working on this, I just have less time now that I'm back in real life.

**Comment by freakboy3742** [comment]
I'm going to close this PR; firstly, we've now found a way to access .NET APIs directly instead of using Win32; and secondly, we've transitioned to CSS-based layout which would require major changes to this PR.

Apologies for taking so long to respond to this, and even though we're not going to use the patch, thanks for the contribution.

**Pull request closed without merging**
